### ISSUE TITLE
undefined local variable or method `pipeline' for #<ActionView::Base:0x007fa36bf7a858>

### ISSUE THREAD

**Issue by kikyous** [rails-engine/flow_core#14]
我访问的url是http://localhost:3000/workflows/5/transitions/11
![image](https://user-images.githubusercontent.com/818616/118801876-13d16680-b8d4-11eb-90bf-0489b3f02eae.png)

**Comment by jasl** [comment]
好累 我到家看眼，你这个 transistions 的类型是啥？

**Comment by kikyous** [comment]
![image](https://user-images.githubusercontent.com/818616/118802599-e33dfc80-b8d4-11eb-9358-d9a63ddf4d32.png)

**Comment by jasl** [comment]
收到

**Comment by kikyous** [comment]
另外问一下这个项目有讨论群什么的吗，我刚启动起来，感觉很厉害，但是文档太简单了，看了也不懂啊

**Comment by jasl** [comment]
> 另外问一下这个项目有讨论群什么的吗，我刚启动起来，感觉很厉害，但是文档太简单了，看了也不懂啊

没有，一般都是在 RubyConf 的微信群 或者 RubyChina 上直接 at 我，或者有我微信的直接问我了，我认识一些做 ToB 系统的朋友，但是这圈子太小了...

**Comment by kikyous** [comment]
再问一下form_core能实现实体之间的关联吗，比如一个form可以选择另一个form创建的实体

**Comment by jasl** [comment]
> 再问一下form_core能实现实体之间的关联吗，比如一个form可以选择另一个form创建的实体

可以，不过我之前卖了两套，所以就没开源了，包括 ransack 那个程度的搜索都有

**Comment by kikyous** [comment]
> > 再问一下form_core能实现实体之间的关联吗，比如一个form可以选择另一个form创建的实体
> 
> 可以，不过我之前卖了两套，所以就没开源了，包括 ransack 那个程度的搜索都有

那确实很牛，比现在的一些代码平台都强

**Comment by jasl** [comment]
实在不会（主要是没空）写好前端，Demo 胡搞的，凑合修一下，试试看
