### ISSUE TITLE
使用 pg 时，db migration 会报错

### ISSUE THREAD

**Issue by dnnta** [rails-engine/flow_core#5]
demo 里 sqlite 没有问题，但是使用 pg 就会报错，`PG::UndefinedTable: ERROR:  relation "flow_core_tasks" does not exist`. 应该是创建外建时，对应的 table 还没有创建。

解决办法：在 create_table 后使用 add_foreign_key 创建外键

**Comment by jasl** [comment]
我稍等修复，感谢！

**Comment by jasl** [comment]
已修复！

**Comment by jasl** [comment]
如果还有新的问题，随时开 Issue 或者微信我！感谢

**Comment by jasl** [comment]
啰嗦一句，我在另一个分支写文档，可能要写一阵
https://github.com/rails-engine/flow_core/blob/wip-new-readme/README.zh-CN.md
