### ISSUE TITLE
删除 field 报错

### ISSUE THREAD

**Issue by oslivan** [rails-engine/flow_core#8]
https://github.com/rails-engine/flow_core/blob/a8a51226e194cace6871e4b99fd028d82ecdfb29/test/dummy/app/models/form_kit/field.rb#L7

这里的 `inverse_of: :field_override` 是不是应该改为 `inverse_of: :field`？因为删除 field 的时候会报下面的错误。

![1881614578878_ pic_hd](https://user-images.githubusercontent.com/22423945/109468487-9aca2c00-7aa7-11eb-8779-8da70032181d.jpg)

**Comment by jasl** [comment]
好像是的，我晚上确认一下哈，顺便升级一波依赖

感谢提醒哈～

**Comment by jasl** [comment]
改正了，GraphViz 那个 gem 不兼容 3.0，所以 dummy 先还固定在 2.7.2

**Comment by oslivan** [comment]
> 改正了，GraphViz 那个 gem 不兼容 3.0，所以 dummy 先还固定在 2.7.2

好的，感谢～
